# Generated by Django 5.2.4 on 2025-07-17 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.unit'),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('injured', 'Injured'), ('mia', 'Missing In Action'), ('discharged', 'Discharged')], max_length=20)),
                ('status_description', models.TextField(blank=True)),
                ('status_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
